### ISSUE TITLE
Home APP cannot find the server

### ISSUE THREAD

**Issue by FrankDoersam** [netonjm/HapSharp#6]
Hey,

Now we have begun the broker as well as the server. Unfortunately, ext. with the Devices cannot combine the Home. We have added the sample Devices in accordance with sample to project. In the NodeJs log we receive mistake that the need "Debug". . . is not found. If you can give us here please a tip, or to the test her complete project Folder as a high-level store ZIP. Thank you very much!

Best regards
Frank

**Comment by netonjm** [comment]
It will be great if you could attach some screens and more detailed log

**Comment by FrankDoersam** [comment]
First error on MAC if i run the command "make install":
<img width="523" alt="bildschirmfoto 2018-03-05 um 18 37 28" src="https://user-images.githubusercontent.com/16541879/36990235-51aeaeca-20a4-11e8-98e8-4df4a03e951d.png">

**Comment by netonjm** [comment]
I fixed this in the guide: 

make install-mac

will work :-)

**Comment by FrankDoersam** [comment]
Thank you for quick reply :) this works!
<img width="467" alt="bildschirmfoto 2018-03-05 um 18 40 03" src="https://user-images.githubusercontent.com/16541879/36990328-a9d83076-20a4-11e8-8fc7-2644e412defd.png">

Could you please send the link, where I could download the current Hap-JS Version, which you already test ?

**Comment by netonjm** [comment]
Your next step is :

make configure

https://github.com/netonjm/HapSharp/#setup-guide

**Comment by FrankDoersam** [comment]
okay, I get the following error:
<img width="520" alt="bildschirmfoto 2018-03-05 um 18 42 42" src="https://user-images.githubusercontent.com/16541879/36990459-0b7d3722-20a5-11e8-8b63-b5f088923212.png">

**Comment by netonjm** [comment]
Could we continue the conversation over:

https://gitter.im/mono/HapSharp

**Comment by netonjm** [comment]
Ok, the problem was you were downloading the project and not cloning the solution, then git was not detecting your folder synching submodules. I will add this to the guide
